/**
 * useChat 对外 API 冻结清单（M0 基线；重构时键名不得删改）。
 */

export const USE_CHAT_OPTS_KEYS = [
  "autoFollowMainRef",
  "onNewChatScrollReset",
  "getPreferredGroupForNewConversation",
  "chatPathname",
  "onNavigateToNewChatSurface",
] as const;

export const USE_CHAT_RETURN_KEYS = [
  "messages",
  "setMessages",
  "hasStarted",
  "chatSurfacePhase",
  "urlConversationId",
  "conversationRouteSynced",
  "messagesLoading",
  "listLoading",
  "sessionRestorePending",
  "genState",
  "conversationId",
  "inputBarUsageHint",
  "serverConversations",
  "isGeneratingTitle",
  "lastAssistantMessageId",
  "followUpSuggestions",
  "followUpsLoadingForId",
  "deleteTargetId",
  "deletePending",
  "bulkDeletePending",
  "movePendingId",
  "conversationFolders",
  "pinnedIds",
  "deepThinkEnabled",
  "setDeepThinkEnabled",
  "webSearchEnabled",
  "setWebSearchEnabled",
  "webSearchMode",
  "setWebSearchMode",
  "chatModelCatalog",
  "chatAgentId",
  "setChatAgentId",
  "selectedProviderId",
  "selectedChatModelId",
  "setModelPick",
  "pendingImageUrls",
  "attachmentUploadBusy",
  "attachmentUploadSkeletonCount",
  "attachmentUploadSlotProgress",
  "pushImageAttachments",
  "removePendingImageUrlAt",
  "applyComposerAttachmentsFromUserMessage",
  "fetchAiImageQuickPrompts",
  "handleWidgetAnswer",
  "handleSend",
  "handleStop",
  "handleRegenerateAssistant",
  "handleNewChat",
  "handleSelectConversation",
  "refreshServerConversations",
  "openDeleteDialog",
  "closeDeleteDialog",
  "confirmDeleteConversation",
  "moveConversationToGroup",
  "createFolder",
  "renameFolder",
  "deleteFolder",
  "togglePinConversation",
  "deleteConversationsBulk",
  "sseRouteAssignPending",
] as const;
